export const state = {
  allStudents: [],
  studentById: new Map(),
  selectedId: null,
  authInfo: null,
  studentFeeSummary: null,
  razorpayKeyId: null,
  feePoliciesByStudent: {},
  portalMode: "student",
  alumniSelectedIds: new Set(),
  selectedStudentIds: new Set(),
  announcementPollTimer: null,
  latestAnnouncementIdSeen: Number(localStorage.getItem("latestAnnouncementIdSeen") || 0),
  announcementsNotifierBootstrapped: false,
  admissionsCache: [],
  attendanceQueueFlushing: false,
  deferredInstallPrompt: null,
  toastTimer: null,
  leadsState: {
    cache: [],
    statusFilter: "all",
    upcomingOnly: false,
  },
  parentMode: false,
  studentProfileCache: null,
  chatbotState: {
    initialized: false,
    step: "greeting",
    intent: "",
    aiAvailable: true,
    profile: { name: "", age: "", qualification: "", location: "", phone: "", preferred_time: "" },
  },
  currentAttempt: null,
  currentAttemptQuestions: [],
  currentAttemptTimer: null,
  malpracticeAutoSubmitted: false,
};
